--- 
javascripts: 
- base: 
  - rails
  - highlight.pack
- panel:
  - jquery.markitup.pack
  - markitup.set
stylesheets: 
- ie: 
  - ie
- screen:
  - screen
- print:
  - print
- panel:
  - textile_style
  - markitup_style
